---

- include_vars: debian.yml
  when: ansible_os_family == "Debian"
  tags: [ openldap, openldap-configure ]

- name: Generating ldap.conf
  template:
    src: etc/ldap/ldap.conf.j2
    dest: "{{ openldap_conf_dir }}/ldap.conf"
    mode: 0644
  when: openldap_conf_file_values
